apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-practice
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: argocd-practice
  template:
    metadata:
      labels:
        app: argocd-practice
    spec:
      containers:
      - image: nginx:1.17
        name: argocd-practice
        ports:
        - containerPort: 80